Updated my part of the silly-bus
ucfai/gbms pull request #17
Opened 2021-02-23 01:20 UTC by DillonNotDylan

2021-02-23 04:13 UTC, brandons209 requested changes

2021-02-23 04:13 UTC, brandons209 commented on sp21/syllabus.yml
> +    In the wonderful world of AI, there are so many oppotunities one has to apply their AI knowledge. Let's discuss what some of those opportunities are!
Could you add a bit more about applications part? Like just add we will be discussing how AI is used today and what not.

2021-02-27 19:43 UTC, DillonNotDylan commented
ok I added a bit to the description

2021-02-27 19:44 UTC, brandons209 approved these changes

2021-02-27 19:44 UTC, merged